import { Inter } from "next/font/google";
import "@/styles/globals.css";
const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });
export const metadata = {
  title: "code213-cryptocurrency",
  description: "Generated by Shadow",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="text-white text-[3rem] text-center mb-[3rem]">
          <span className="text-green-400">Crypto </span>
          Shadow
        </h1>
        {children}
      </body>
    </html>
  );
}
